wp mode in the plugin in order to import scripts for monsieur-wifi.com
Groupe-Citypassenger-Inc/digilan-token pull request #23
Opened 2021-04-28 19:19 UTC by rsoultan

If you want to enable wp mode, you need to insert on the wp-options table a row with option_name = "mode" and option_value = "wp".

The wp mode will trigger javascript scripts importation on specific pages (for now, /speedtest).

2021-04-28 19:27 UTC, dohnuts requested changes

2021-04-28 19:27 UTC, dohnuts commented on digilan-token.php
> +
Good

2021-04-28 19:27 UTC, dohnuts commented on js/speedtest.js
> +        alert("JQuery est import !");
surement pas , pas de truc de dev test dans le code, cela degage merci

2021-04-28 19:27 UTC, dohnuts commented on digilan-token.php
> +        }
correct mais 'wp' comme nom de mode  c est ultra pas clair, et tu peux pas avoir genre deux trois mode mélangé

if $mode contient inject_speed_test serait mieux, merci de modifier

2021-04-28 19:39 UTC, rsoultan commented
Je fais ça demain matin ! Merci pour les feedbacks

2021-05-05 12:42 UTC, dohnuts requested changes

2021-05-05 12:42 UTC, dohnuts commented on js/speedtest/speedtest.js
> +	    this._settings[parameter] = value;
indentation

2021-05-05 12:42 UTC, dohnuts commented on js/speedtest/speedtest.js
> +      }
indentation + unclear variable name 'state' who should just be the length of the serve list ( state is irrelevant )

2021-05-05 12:42 UTC, dohnuts commented on js/speedtest/speedtest.js
> +			        (bestServer == null || serverList[i].pingT < bestServer.pingT)) {
cant read

2021-05-05 12:42 UTC, dohnuts commented on js/speedtest/speedtest_worker.js
> +};
indent

2021-05-05 12:42 UTC, dohnuts commented on js/speedtest/speedtest_worker.js
> +var log = "";
remove si log var if possible : console.log for debug and nothing in prod

2021-05-05 12:42 UTC, dohnuts commented on js/speedtest/speedtest_worker.js
> +    tlog("IP: " + xhr.responseText + ", took " + (new Date().getTime() - startT) + "ms");
tout ce code en vrac pour pas mettre une lib qui fait de l ajax => une justification ?

2021-05-05 12:42 UTC, dohnuts commented on js/speedtest/speedtest_worker.js
> +    xhr.send(postData);
je pense pas qu on veuille envoyer ces infos dans la nature

2021-05-07 17:12 UTC, closed without merging