add update ap functions
Groupe-Citypassenger-Inc/digilan-token pull request #31
Opened 2021-07-07 14:25 UTC by Jamesjin18

2021-07-08 13:46 UTC, dohnuts requested changes
error line 1, i dont bother getting further

2021-07-08 15:25 UTC, Jamesjin18 commented on digilan-token-multi-portal.php
> +            $access_points[$key] = array_merge($access_points[$key],$new_data);
je vois pas pourquoi on aurait des timeout differents puis new_data ecraser les anciens config

2021-07-09 15:12 UTC, Jamesjin18 commented
[test2.zip](https://github.com/Groupe-Citypassenger-Inc/digilan-token/files/6792329/test2.zip)

2021-07-09 15:16 UTC, dohnuts requested changes
Presque bon

2021-07-09 15:16 UTC, dohnuts commented on digilan-portal-model.php
> +    {
il faut rajouter un validateur de donnée ici

2021-07-09 15:16 UTC, dohnuts commented on digilan-token-multi-portal.php
> +        }
maybe_unserialize mais tu test quand meme, je pense que tout cela est bien compliqu;e pour pas grande chose,

2021-07-09 15:16 UTC, dohnuts commented on digilan-token-multi-portal.php
> +        }
code dupliqué sns importantce fait toi un get_valide_get_user_meta .. et fait juste DIE dedans au lieu de return cela va redurie le code enormement => moins de code =>moins de probleme

2021-07-12 09:50 UTC, Jamesjin18 commented
[test2.zip](https://github.com/Groupe-Citypassenger-Inc/digilan-token/files/6800385/test2.zip)

2021-07-12 13:50 UTC, dohnuts requested changes
presque bon

2021-07-12 13:50 UTC, dohnuts commented on digilan-portal-model.php
> +        }
error_log est insuffisant, il die / car tu est dans un constructeur, le call a sanitize peut etre fait dans une methode post construction poru return undef si tu as besoin , mais DIE/quit/expect est ok aussi

2021-07-12 13:50 UTC, dohnuts commented on digilan-token-multi-portal.php
> +        }
return $user .... as bool , or cast... bref l equivalent pp de return (bool)$user

2021-07-12 16:12 UTC, dohnuts requested changes

2021-07-12 16:12 UTC, dohnuts commented on digilan-portal-model.php
> +        $re = '';
sert a quoi ce truc ?

2021-07-12 16:12 UTC, dohnuts commented on digilan-token-multi-portal.php
> +            die();
ici die est trop , demander un truc qui est vide est pas un exception,  get_client_ap_list_from_hostname > return empty c est normal....

2021-07-12 16:12 UTC, dohnuts commented on digilan-token-multi-portal.php
> +                die();
ce die est encore violent, passable mais violent,

2021-07-12 16:12 UTC, dohnuts commented on includes/digilan-sanitize.php
> +                    if ($res === null) {
utlise le DOUBLE egal pour null ou false.

2021-07-12 16:12 UTC, dohnuts commented on includes/digilan-sanitize.php
> +                    return self::sanitize_url($unsafe_value);
ce esc_url_raw commit a rien a voir avec la class d en haut :S

2021-07-12 16:12 UTC, dohnuts commented on includes/digilan-sanitize.php
> +                    return self::sanitize_url($unsafe_value);
si c est buggé faire une autre PR a part, y a zero rapport

2021-07-13 12:15 UTC, dohnuts commented
A model for Portal Configs

2021-07-13 12:16 UTC, merged