change api function to use new model settings
Groupe-Citypassenger-Inc/digilan-token pull request #33
Opened 2021-07-21 10:57 UTC by Jamesjin18

2021-07-21 10:59 UTC, Jamesjin18 commented
[test.zip](https://github.com/Groupe-Citypassenger-Inc/digilan-token/files/6855035/test.zip)

2021-07-21 12:51 UTC, dohnuts commented on includes/digilan-activator.php
> +            var_dump($data);
pas dans le code ... y a d autre moyen en plus

2021-07-21 12:54 UTC, dohnuts requested changes

2021-07-21 12:54 UTC, dohnuts commented on includes/digilan-activator.php
> +            var_dump($data);
https://developer.wordpress.org/reference/classes/wp_error/ a vori et praobalement le DEBUG=1 dans la conf d ebase du truc en test

2021-07-21 12:54 UTC, dohnuts commented on includes/digilan-activator.php
> +            var_dump($data);
👎

2021-07-21 12:54 UTC, dohnuts commented on digilan-portal-model.php
> +    function __construct(string $ssid, string $mac, string $access,  string $country_code, string $schedule, string $portal ='captive-portal', string $landing='', int $timeout=7200,  string $schedule
put back error page

2021-07-21 15:36 UTC, Jamesjin18 commented
[test.zip](https://github.com/Groupe-Citypassenger-Inc/digilan-token/files/6856986/test.zip)

2021-07-21 15:47 UTC, dohnuts requested changes

2021-07-21 15:47 UTC, dohnuts commented on includes/digilan-activator.php
>          $data = wp_json_encode($data);
tu as mis le schedule dans le modele mais tu mets dans intervals ?

met donc $ap_setting_array['ap_settings'] dans une variable  temporaire

pas trop sur que je vois marche avec les veilles donnée dans le code

2021-07-21 15:47 UTC, dohnuts commented on includes/digilan-connection.php
> +        return $user_id;
foreach er retourne que 1 ?? il y a  d autre method que get_rsultS  pour les trucs a une seule entré

peut etre https://developer.wordpress.org/reference/classes/wpdb/get_var/ ?

2021-07-21 15:56 UTC, Jamesjin18 commented on includes/digilan-activator.php
>          $data = wp_json_encode($data);
interval est initialiser mais n'est jamais utiliser

2021-07-21 15:56 UTC, Jamesjin18 commented on includes/digilan-activator.php
>          $data = wp_json_encode($data);
je l'enleve donc

2021-07-22 13:52 UTC, dohnuts commented on includes/digilan-connection.php
> +        }
https://www.php.net/manual/en/function.array-search.php ? ou similaire ?

2021-07-22 13:52 UTC, dohnuts commented on includes/digilan-connection.php
> +    }
mieux

2021-07-22 13:53 UTC, dohnuts commented on includes/digilan-connection.php
> +        $hostname = self::get_hostname_with_mac($ap_mac);
a quaoi cela sert ?

2021-07-22 13:54 UTC, dohnuts commented on includes/digilan-activator.php
> +        $global_settings = $ap_setting_array['global_settings'];
global c est partager entre les ap ?

donc shared_settings ? 

et ap c estpour un ap specific ?  mais ou est le if ( not ap_ ) use global ?

2021-07-22 13:54 UTC, dohnuts commented on includes/digilan-activator.php
> +            $new_ap_settings = new DigilanPortalModel('Borne Autonome',$mac,current_time('mysql'), 'FR', '{"0":[],"1":[],"2":[],"3":[],"4":[],"5":[],"6":[]}');
pourquoi ne pas creer un model qui donne glocal ou ap en fonction de si c est init ou pas et appres toujours utilisé une VUE du model en bas ?

2021-07-22 13:55 UTC, dohnuts commented on includes/digilan-activator.php
> +            'error_page' => $global_settings['error_page'],
devrait etre data = Model->view ( params eventuell )

2021-07-22 13:55 UTC, dohnuts requested changes
voir comments

2021-07-22 14:26 UTC, Jamesjin18 commented on includes/digilan-connection.php
> +        $hostname = self::get_hostname_with_mac($ap_mac);
ca sert a avoir l'hostname à partir du mac client

2021-07-22 14:30 UTC, dohnuts commented on includes/digilan-connection.php
> +        $hostname = self::get_hostname_with_mac($ap_mac);
Je ne vois pas d usage de ces variables en dessous, dans la diff ni une diff qui eneleve l init au dessus , il faut l un ou lautre ...

2021-07-23 12:34 UTC, dohnuts commented on digilan-portal-model.php
> +        return $vue;
return array_map('get_setting', $keys);

2021-07-23 12:37 UTC, dohnuts commented on includes/digilan-activator.php
>          $data = wp_json_encode($data);
pourquoi schedule est hors model ?

2021-07-23 12:41 UTC, dohnuts requested changes

2021-07-23 12:41 UTC, dohnuts commented on includes/digilan-connection.php
> +
duplica logiquement incompatible de get_ids_from_mac plus bas , si on veut que un id il faut limit 1 et explié pourquoi les autres id sont ignoré

2021-07-26 14:39 UTC, dohnuts requested changes
mieux mais toujours beaucoup de code pas clair et/ou qui fait pas de sens

le code devrait etre tres clair et lisible car il y a pas grand chose .

2021-07-26 14:39 UTC, dohnuts commented on digilan-portal-model.php
> +        }
????????????

2021-07-26 14:39 UTC, dohnuts commented on includes/digilan-connection.php
> +    }
comprend pas , les anciens settings semble ignoré et le nom de la fonction est pas comprehensible cela retourne un KEY  et le truc s appelle get_hostname....

2021-07-26 14:39 UTC, dohnuts commented on includes/digilan-connection.php
> +    }
faut renommer KEY en hostname...

2021-07-26 14:39 UTC, dohnuts commented on includes/digilan-connection.php
> +    }
et appeler get_hostname_from_mac
avec kle commenatire , try to find a specific setting for a mac , and return the hostname 
( si c est ce que cela fait )

2021-07-26 14:39 UTC, dohnuts commented on includes/digilan-connection.php
>              }
fix les espaces pour pas que cela se voit dans la diff

2021-07-26 14:39 UTC, dohnuts commented on includes/digilan-connection.php
> +                $global_settings = $specific_settings-> get_ap_params($global_settings);
$global_settings = $specific_settings-> get_ap_params($global_settings);

je ne comprend pas pouruqoi tu garde  le nom global settings ici , c est pas clair=>

$calling_ap_settings = $specific_settings-> get_ap_params($global_settings);

2021-07-27 13:46 UTC, dohnuts approved these changes
A valider avec Matt

2021-07-27 13:46 UTC, dohnuts commented on digilan-portal-model.php
> +        }
ce genre de truc peut etre gerer ailleurs, mais sans importance

2021-07-27 13:46 UTC, dohnuts commented on digilan-portal-model.php
> +    {
j eu appelé cela replace_IF_specific_setting

2021-07-27 13:46 UTC, dohnuts commented on digilan-portal-model.php
>          }
doncla faut le this mais dans array_walk . php ✨

2021-07-27 13:47 UTC, merged